#!/bin/bash 

####################
#This is just to generate user information
echo "Enter Name"
read Name
echo "Enter Age"
read Age
echo "Enter Mail"
read Mail
echo "Enter Paasword"
read Password

echo "NAME: $Name"
echo "Age: $Age"
echo "Date: $Mail"
echo "Purpose: $Password"

echo "Your mail has been verified!! WELCOME USER $Name to ENZOTECTOK
