#!/bin/bash

#############################################
#Author: Lateef
#Date: 21, march, 2024
#Purpose: To test variable and how to use them 


Name="Ajala"
age=22
work="student"
height=5.2
school="Lagos state university"

echo $Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall $Name "is" $age years and he is a $work of $school. He is $height ft tall $Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall$Name "is" $age years and he is a $work of $school. He is $height ft tall
